version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URI=mongodb://mongo:27017/property
      - REDIS_URL=redis://redis:6379
      - PORT=5000
      - NODE_ENV=production
      # Add other env variables or mount .env file
