services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/property
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    volumes:
      - ./logs:/app/logs

  mongo:
    image: mongo:latest
    container_name: mongo-server
    restart: always
    ports:
      - '28017:27017'
    command: ['mongod', '--bind_ip', '0.0.0.0']
    environment:
      MONGO_INITDB_DATABASE: property
    networks:
      - backend_network
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    networks:
      - backend_network
    ports:
      - '6379:6379'
    
volumes:
  mongo_data:
  redis_data:


networks:
  backend_network:
    driver: bridge